twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_title: '%env(resolve:APP_TITLE)%'

when@test:
    twig:
        strict_variables: true
