twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_title: '%env(resolve:APP_TITLE)%'
        app_privacy_url: '%env(resolve:APP_PRIVACY_URL)%'
        app_imprint_url: '%env(resolve:APP_IMPRINT_URL)%'

when@test:
    twig:
        strict_variables: true
